# fly.toml app configuration file generated for bloghubbackend on 2024-07-24T20:46:31+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bloghubbackend'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.http_routes]]
    path = "/*"
    destination_port = 3000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
