name: CI pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Start server in background
        run: |
          npm start &
          sleep 10
        working-directory: ./backend
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          PORT: ${{ secrets.PORT }}

      - name: Wait for server to start
        run: sleep 10

      - name: Build frontend
        run: |
          npm run dev &
          sleep 10
        working-directory: ./frontend

      - name: Wait for frontend to start
        run: sleep 10

      - name: Deploy the frontend
        run: flyctl deploy --remote-only
        working-directory: ./frontend
        env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy the backend
        run: flyctl deploy --remote-only
        working-directory: ./backend
        env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN2 }}

      - name: The job has succeeded
        if: ${{ success() }}
        run: echo "Success!"
        
